EnvironmentalConditions:
  ambient_illumination:
    - is_set
  time_of_day:
    - is_set
  atmospheric_pressure:
    - is_set
    - in_range: [800e+2, 1200e+2]
  temperature:
    - is_set
    - in_range: [170, 340]
  relative_humidity:
    - is_set
    - in_range: [0, 100]
  precipitation:
    - is_set
  fog:
    - is_set
  TimeOfDay:
    seconds_since_midnight:
      - in_range: [0, 86400, ro]